- name: create dirs to Dockerfile - images to build
  file:
     path:  "{{ docker.build.build_path }}/{{ item.value.name }}"
     state: directory
     mode:  0777
  with_dict:  "{{ docker.build.images_to_build }}"
  when:
     item.value.build == True

- include: "gen_files.yml"

#
# Fail
- fail:
    msg: "Stop"

- name: Template Dockerfile for images to build
  template:
     src:  Dockerfile.j2
     dest: "{{ docker.build.build_path }}/{{ item.value.name }}/Dockerfile"
  with_dict:  "{{ docker.build.images_to_build }}"
  when:
     item.value.build == True

- name: Build image and with buildargs
  docker_image:
     path:  "{{ docker.build.build_path }}/{{ item.value.name }}"
     name: "{{ item.value.repo }}/{{ item.value.name }}"
     tag:  "{{ item.value.tag }}"
     pull: False
  with_dict:  "{{ docker.build.images_to_build }}"
  when:
     item.value.build == True
