#
# Generate up tp 3 files for each image

- name: Create files needed to build - create template files - 1
  debug:
    msg:  "create file for {{ item }}"
  # copy:
  #   content: "{{ item.value.files.cnt }} "
  #   dest:    "{{ docker.build.build_path }}/{{ item.value.name }}/{{ item.value.files.cnt }} "
  #   mode:  0777
  with_items:  "{{ docker | json_query(my_query)}}"
  vars:
    my_query: "build.images_to_build.*.files.*.dst"




    #  with_items: "{{domain_definition|json_query('domain.server[*].name')}}"

    # my_query: "files"
  # when:
  #    item.value.build == True
  #    item.value.files is defined and
  #    item.value.files[0] is defined
